stages:
  - test
  - build
  - deploy

image: docker:19.03.10
services:
  - docker:18.09-dind

build:
  stage: build
  image:
    name: node:14-alpine
  cache:
    paths:
      - .npm
      - cache/Cypress
      - node_modules
  artifacts:
    paths:
      - dist
      - node_modules
    expire_in: 1 week
  before_script:
    - npm ci
  script:
    - npm run build

test:
  image: node:latest
  stage: test
  script:
    - echo $NEXT_PUBLIC_API_HOST
    - npm ci
    - npm run e2e:run
  cache:
    paths:
      - .npm
      - cache/Cypress
      - node_modules

deploy:
  stage: deploy
  image: node:14-alpine
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/client-side-next-js-project.git HEAD:master
    - deployed to the heroku server
  variables:
    NEXT_PUBLIC_API_HOST: $NEXT_PUBLIC_API_HOST
  only:
    - master
