stages:
  - test
  - build
  - deploy

image: docker:19.03.10
services:
  - docker:18.09-dind

build:
  stage: build
  image:
    name: node:14-alpine
  artifacts:
    paths:
      - dist
      - node_modules
    expire_in: 1 week

  cache:
    paths:
      - node_modules
  before_script:
    - npm ci
  script:
    - npm run build

test:
  stage: test
  image: cypress/browsers:node12.14.1-chrome85-ff81
  script:
    - npm run cypress:run

deploy:
  stage: deploy
  image: node:14-alpine
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/client-side-next-js-project.git HEAD:master
    - deployed to the heroku server
  only:
    - master
