stages:
  - test
  - build
  - deploy

variables:
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

image: docker:19.03.10
services:
  - docker:18.09-dind

build:
  stage: build
  image:
    name: node:14-alpine
  artifacts:
    paths:
      - dist
      - node_modules
    expire_in: 1 week
  before_script:
    - npm ci
  script:
    - npm run build

test:
  image: node:latest
  stage: test
  script:
    - npm ci
    - npm run start:ci &
    - npm run e2e

deploy:
  stage: deploy
  image: node:14-alpine
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/client-side-next-js-project.git HEAD:master
    - deployed to the heroku server
  variables:
    NEXT_PUBLIC_API_HOST: https://radiant-oasis-74595.herokuapp.com/graphql
  only:
    - master
