version: '3.7'

services:
  client:
    container_name: next
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
