import 'styles/globals.scss'
import 'react-tabs/style/react-tabs.css'
import type { AppProps } from 'next/app'
import BaseLayout from 'src/layout/BaseLayout'
import Head from 'next/head'
import { apolloClient } from 'src/apollo/apollo-client'
import { ApolloProvider } from '@apollo/client'
import { AuthProvider } from 'src/context/auth'
import NextNprogress from 'nextjs-progressbar'

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>NEXT APP</title>
				<meta
					name="viewport"
					content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover"
				/>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/images/favicon.ico" />
			</Head>
			<AuthProvider>
				<ApolloProvider client={apolloClient}>
					<BaseLayout>
						<NextNprogress
							color="#29D"
							startPosition={0.3}
							stopDelayMs={200}
							height={3}
							showOnShallow={true}
							options={{ easing: 'ease', speed: 500 }}
						/>
						<Component {...pageProps} />
					</BaseLayout>
				</ApolloProvider>
			</AuthProvider>
		</>
	)
}
export default MyApp
